### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by CPSibo** [fauna/vscode#37] opened 2020-08-08 02:02 UTC
### Summary
Any action attempted on versions after 1.1.0 throw an error about commands not being found.

### Details
Installing any version of this extension between 1.2.0 and 1.3.2 (latest) throws exceptions when trying any extension action.

For instance, trying to refresh the list of databases gives: `command 'faunadb.refreshEntry' not found`
Trying to create a query gives: `Command 'FaunaDB: Create Query' resulted in an error (command 'faunadb.createQuery' not found)`

However, installing the 1.1.0 version works just fine with the same global settings. It's able to browse my databases and run commands.

I've tried reinstalling the extension entirely, creating new admin keys, and refreshing the database listing with and without data in the account.

### Environment
OS: Kubuntu 19.10 64-bit
VSCode: 1.47.3
Fauna: 1.2.0 - 1.3.2

**Comment by BrunoQuaresma** [comment] 2020-08-11 17:14
Thanks @CPSibo for let us know. I opened a ticket for our team to take a look on this.

**Comment by BrunoQuaresma** [comment] 2020-08-19 16:28
@CPSibo I was not able to reproduce the error using 1.3.2.

My VSCode config:
```
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z (6 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Closing until other users report this again.

**Closed by BrunoQuaresma** 2020-08-19 16:28 UTC
Labels: bug

**Comment by JerryGreen** [comment] 2020-11-05 13:16
I faced the same bug when I JUST INSTALLED the extension. But after I restarted VSCode, it works ok now.
